# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: funsearch_worker/pb/funsearch.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'funsearch_worker/pb/funsearch.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#funsearch_worker/pb/funsearch.proto\x12\x13\x66unsearch_worker.pb\"J\n\tCandidate\x12\x12\n\nhypothesis\x18\x01 \x01(\t\x12\x14\n\x0cquantitative\x18\x02 \x01(\x01\x12\x13\n\x0bqualitative\x18\x03 \x01(\t\"X\n\x0eProposeRequest\x12/\n\x07parents\x18\x01 \x03(\x0b\x32\x1e.funsearch_worker.pb.Candidate\x12\x15\n\rspecification\x18\x02 \x01(\t\"\'\n\x0fProposeResponse\x12\x14\n\x0chypothesises\x18\x01 \x03(\t\"$\n\x0eObserveRequest\x12\x12\n\nhypothesis\x18\x01 \x01(\t\"P\n\x0fObserveResponse\x12\x12\n\nhypothesis\x18\x01 \x01(\t\x12\x14\n\x0cquantitative\x18\x02 \x01(\x01\x12\x13\n\x0bqualitative\x18\x03 \x01(\t2\xbb\x01\n\tFUNSEARCH\x12V\n\x07propose\x12#.funsearch_worker.pb.ProposeRequest\x1a$.funsearch_worker.pb.ProposeResponse\"\x00\x12V\n\x07observe\x12#.funsearch_worker.pb.ObserveRequest\x1a$.funsearch_worker.pb.ObserveResponse\"\x00\x42\'Z%funsearch-orchestrator/internal/pb;pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'funsearch_worker.pb.funsearch_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z%funsearch-orchestrator/internal/pb;pb'
  _globals['_CANDIDATE']._serialized_start=60
  _globals['_CANDIDATE']._serialized_end=134
  _globals['_PROPOSEREQUEST']._serialized_start=136
  _globals['_PROPOSEREQUEST']._serialized_end=224
  _globals['_PROPOSERESPONSE']._serialized_start=226
  _globals['_PROPOSERESPONSE']._serialized_end=265
  _globals['_OBSERVEREQUEST']._serialized_start=267
  _globals['_OBSERVEREQUEST']._serialized_end=303
  _globals['_OBSERVERESPONSE']._serialized_start=305
  _globals['_OBSERVERESPONSE']._serialized_end=385
  _globals['_FUNSEARCH']._serialized_start=388
  _globals['_FUNSEARCH']._serialized_end=575
# @@protoc_insertion_point(module_scope)
