[tool.poetry]
name = "mictlan"
version = "0.1.0"
description = ""
authors = ["Xolotl <xolotl.mictl4n@gmail.com>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
# 共有するパッケージはPEPに準拠してインストール可能にしdependencesに追加する
util = { path = "./packages/util/python", develop = true }
syuron = { path = "./apps/syuron/python", develop = true, optional = true }
notebook = "^7.2.2"

[tool.poetry.extras]
gpu = [
    "syuron", # 機械学習するため必要
]

[tool.pyright]
# pylanceはここで指定したフォルダ内のファイルのみ検出する
include = [
    "**/python",
    "scripts",
    "build",
    "apps/personal-site/web/notebook",
    "apps/syuron",
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
