[tool.poetry]
name = "mictlan"
version = "0.1.0"
description = ""
authors = ["Xolotl <xolotl.mictl4n@gmail.com>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
# 共有するパッケージはPEPに準拠してインストール可能にしdependencesに追加する
infra = { path = "./infra", develop = true }
util = { path = "./packages/util/python", develop = true }
quantum = { path = "./research/quantum", develop = true }
chathub = { path = "./apps/chathub", develop = true }
fssearch = { path = "./apps/fssearch", develop = true }
noteprez = { path = "./apps/noteprez", develop = true }
syuron = { path = "./research/syuron/python", develop = true, optional = true }
notebook = "^7.2.2"
nbconvert = "^7.16.4"
playwright = "^1.48.0"

[tool.poetry.extras]
gpu = [
    "syuron", # 機械学習できる環境のみ
]

[tool.pyright]
# pylanceはここで指定したフォルダ内のファイルのみ検出する
include = [
    "infra",
    "**/python",
    "scripts",
    "build",
    "apps/personal-site/web/notebook",
    "apps/noteprez",
    "apps/fssearch",
    "apps/chathub",
    "research/leetcode",
    "research/quantum",
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
