[project]
name = "mictlan"
version = "0.1.0"
description = "all in one monorepo"
authors = [{ name = "Xolotl", email = "xolotl.mictl4n@gmail.com" }]
requires-python = ">=3.12"
dependencies = [
    "notebook",
    "nbconvert",
    "playwright",
    "plotly",
    "jax[cuda]",
    "optax",
    "pandas",
    "japanize_matplotlib",

    # libはworkspaceの依存とすることで自動でインストールできる、sourcesへの追加も必要
    "syuron",
    "funsearch",
    "blog",
    "akinator",
    "qpm",
]

[project.optional-dependencies]
gpu = ["syuron"]

[tool.uv]
package = false

[tool.uv.workspace]
members = [
    "infra",
    "packages/util/python",
    "packages/workspace",
    "apps/akinator",
    "apps/blog",
    "research/syuron",
    "research/funsearch",
    "research/qpm",
]

[tool.uv.sources]
syuron = { workspace = true }
funsearch = { workspace = true }
blog = { workspace = true }
akinator = { workspace = true }
qpm = { workspace = true }

[tool.pyright]
include = [
    "infra",
    "packages/util/python",
    "scripts",
    "build",
    "apps/akinator",
    "research/syuron",
    "research/qpm",
    "packages/workspace",
    "research/funsearch",
]
# reportIncompatibleMethodOverride = true
# reportAbstractUsage = true
# reportMissingTypeArgument = "error"
# reportUnknownVariableType = "error"
