[project]
name = "mictlan"
version = "0.1.0"
description = ""
authors = [{ name = "Xolotl", email = "xolotl.mictl4n@gmail.com" }]
requires-python = ">=3.12"
dependencies = [
    "notebook>=7.3.3",
    "nbconvert>=7.16.6",
    "playwright>=1.51.0",

    # libというよりはアプリケーションなものはworkspaceの依存とすることで自動でインストールできる、sourcesへの追加も必要
    "syuron",
    "funsearch",
    "quantum",
    "noteprez",
    "blog",
    "akinator",
    "fssearch",
]

[project.optional-dependencies]
gpu = ["syuron"]

[tool.uv]
package = false

[tool.uv.workspace]
members = [
    "infra",
    "packages/util/python",
    "packages/workspace",
    "research/quantum",
    "apps/chathub",
    "apps/fssearch",
    "apps/noteprez",
    "apps/akinator",
    "apps/blog",
    "research/syuron",
    "research/funsearch",
]

[tool.uv.sources]
syuron = { workspace = true }
funsearch = { workspace = true }
quantum = { workspace = true }
noteprez = { workspace = true }
blog = { workspace = true }
akinator = { workspace = true }
fssearch = { workspace = true }

[tool.pyright]
include = [
    "infra",
    "packages/util/python",
    "scripts",
    "build",
    "apps/personal-site/web/notebook",
    "apps/noteprez",
    "apps/akinator",
    "apps/fssearch",
    "apps/chathub",
    "research/leetcode",
    "research/quantum",
    "research/syuron",
    "packages/workspace",
    "research/funsearch",
]
reportIncompatibleMethodOverride = true
reportAbstractUsage = true
