[project]
name = "blog"
version = "0.1.0"
description = ""
authors = [{ name = "Xo1otl", email = "xolotl.mictl4n@gmail.com" }]
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["streamlit>=1.41.1"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
