[project]
name = "syuron"
version = "0.1.0"
description = ""
authors = [{ name = "Xo1otl", email = "xolotl.mictl4n@gmail.com" }]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.2.3",
    "scipy>=1.15.2,<2.0.0",
    "numpy>=2.2.4,<3.0.0",
    "matplotlib>=3.10.1,<4.0.0",
    "jax[cuda12]>=0.5.2",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
