[tool.poetry]
name = "util"
version = "0.1.0"
description = ""
authors = ["Xo1otl <xolotl.mictl4n@gmail.com>"]
readme = "README.md"
packages = [{ include = "util", from = "." }]


[tool.poetry.dependencies]
python = "^3.10"
ipython = "^8.26.0"
numpy = "^2.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
