[project]
name = "noteprez"
version = "0.1.0"
description = ""
authors = [{ name = "Xo1otl", email = "xolotl.mictl4n@gmail.com" }]
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["docling>=2.8.1"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
