[project]
name = "quantum"
version = "0.1.0"
description = ""
authors = [{ name = "Xo1otl", email = "xolotl.mictl4n@gmail.com" }]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "qiskit",
    "qiskit-ibm-runtime",
    "pylatexenc",
    "qiskit-aer",
    "qulacs",
]
