// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: pb/llmsr.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LLMSR_Propose_FullMethodName = "/llmsr_worker.pb.LLMSR/propose"
	LLMSR_Observe_FullMethodName = "/llmsr_worker.pb.LLMSR/observe"
)

// LLMSRClient is the client API for LLMSR service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// llmsr-worker service definition.
type LLMSRClient interface {
	// propose generates new program skeletons based on parent programs.
	Propose(ctx context.Context, in *ProposeRequest, opts ...grpc.CallOption) (*ProposeResponse, error)
	// observe evaluates a given program skeleton and returns its performance score.
	Observe(ctx context.Context, in *ObserveRequest, opts ...grpc.CallOption) (*ObserveResponse, error)
}

type lLMSRClient struct {
	cc grpc.ClientConnInterface
}

func NewLLMSRClient(cc grpc.ClientConnInterface) LLMSRClient {
	return &lLMSRClient{cc}
}

func (c *lLMSRClient) Propose(ctx context.Context, in *ProposeRequest, opts ...grpc.CallOption) (*ProposeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProposeResponse)
	err := c.cc.Invoke(ctx, LLMSR_Propose_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMSRClient) Observe(ctx context.Context, in *ObserveRequest, opts ...grpc.CallOption) (*ObserveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ObserveResponse)
	err := c.cc.Invoke(ctx, LLMSR_Observe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LLMSRServer is the server API for LLMSR service.
// All implementations must embed UnimplementedLLMSRServer
// for forward compatibility.
//
// llmsr-worker service definition.
type LLMSRServer interface {
	// propose generates new program skeletons based on parent programs.
	Propose(context.Context, *ProposeRequest) (*ProposeResponse, error)
	// observe evaluates a given program skeleton and returns its performance score.
	Observe(context.Context, *ObserveRequest) (*ObserveResponse, error)
	mustEmbedUnimplementedLLMSRServer()
}

// UnimplementedLLMSRServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLLMSRServer struct{}

func (UnimplementedLLMSRServer) Propose(context.Context, *ProposeRequest) (*ProposeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Propose not implemented")
}
func (UnimplementedLLMSRServer) Observe(context.Context, *ObserveRequest) (*ObserveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Observe not implemented")
}
func (UnimplementedLLMSRServer) mustEmbedUnimplementedLLMSRServer() {}
func (UnimplementedLLMSRServer) testEmbeddedByValue()               {}

// UnsafeLLMSRServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LLMSRServer will
// result in compilation errors.
type UnsafeLLMSRServer interface {
	mustEmbedUnimplementedLLMSRServer()
}

func RegisterLLMSRServer(s grpc.ServiceRegistrar, srv LLMSRServer) {
	// If the following call pancis, it indicates UnimplementedLLMSRServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LLMSR_ServiceDesc, srv)
}

func _LLMSR_Propose_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProposeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMSRServer).Propose(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMSR_Propose_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMSRServer).Propose(ctx, req.(*ProposeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMSR_Observe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObserveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMSRServer).Observe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMSR_Observe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMSRServer).Observe(ctx, req.(*ObserveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LLMSR_ServiceDesc is the grpc.ServiceDesc for LLMSR service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LLMSR_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "llmsr_worker.pb.LLMSR",
	HandlerType: (*LLMSRServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "propose",
			Handler:    _LLMSR_Propose_Handler,
		},
		{
			MethodName: "observe",
			Handler:    _LLMSR_Observe_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/llmsr.proto",
}
