# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from llmsr_worker.pb import llmsr_pb2 as llmsr__worker_dot_pb_dot_llmsr__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in llmsr_worker/pb/llmsr_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LLMSRStub(object):
    """llmsr-worker service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.propose = channel.unary_unary(
                '/llmsr_worker.pb.LLMSR/propose',
                request_serializer=llmsr__worker_dot_pb_dot_llmsr__pb2.ProposeRequest.SerializeToString,
                response_deserializer=llmsr__worker_dot_pb_dot_llmsr__pb2.ProposeResponse.FromString,
                _registered_method=True)
        self.observe = channel.unary_unary(
                '/llmsr_worker.pb.LLMSR/observe',
                request_serializer=llmsr__worker_dot_pb_dot_llmsr__pb2.ObserveRequest.SerializeToString,
                response_deserializer=llmsr__worker_dot_pb_dot_llmsr__pb2.ObserveResponse.FromString,
                _registered_method=True)


class LLMSRServicer(object):
    """llmsr-worker service definition.
    """

    def propose(self, request, context):
        """propose generates new program skeletons based on parent programs.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def observe(self, request, context):
        """observe evaluates a given program skeleton and returns its performance score.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LLMSRServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'propose': grpc.unary_unary_rpc_method_handler(
                    servicer.propose,
                    request_deserializer=llmsr__worker_dot_pb_dot_llmsr__pb2.ProposeRequest.FromString,
                    response_serializer=llmsr__worker_dot_pb_dot_llmsr__pb2.ProposeResponse.SerializeToString,
            ),
            'observe': grpc.unary_unary_rpc_method_handler(
                    servicer.observe,
                    request_deserializer=llmsr__worker_dot_pb_dot_llmsr__pb2.ObserveRequest.FromString,
                    response_serializer=llmsr__worker_dot_pb_dot_llmsr__pb2.ObserveResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'llmsr_worker.pb.LLMSR', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('llmsr_worker.pb.LLMSR', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LLMSR(object):
    """llmsr-worker service definition.
    """

    @staticmethod
    def propose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llmsr_worker.pb.LLMSR/propose',
            llmsr__worker_dot_pb_dot_llmsr__pb2.ProposeRequest.SerializeToString,
            llmsr__worker_dot_pb_dot_llmsr__pb2.ProposeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def observe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/llmsr_worker.pb.LLMSR/observe',
            llmsr__worker_dot_pb_dot_llmsr__pb2.ObserveRequest.SerializeToString,
            llmsr__worker_dot_pb_dot_llmsr__pb2.ObserveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
