# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: llmsr_worker/pb/llmsr.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'llmsr_worker/pb/llmsr.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bllmsr_worker/pb/llmsr.proto\x12\x0fllmsr_worker.pb\"*\n\x07Program\x12\x10\n\x08skeleton\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x01\";\n\x0eProposeRequest\x12)\n\x07parents\x18\x01 \x03(\x0b\x32\x18.llmsr_worker.pb.Program\"$\n\x0fProposeResponse\x12\x11\n\tskeletons\x18\x01 \x03(\t\"\"\n\x0eObserveRequest\x12\x10\n\x08skeleton\x18\x01 \x01(\t\"2\n\x0fObserveResponse\x12\x10\n\x08skeleton\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x01\x32\xa7\x01\n\x05LLMSR\x12N\n\x07propose\x12\x1f.llmsr_worker.pb.ProposeRequest\x1a .llmsr_worker.pb.ProposeResponse\"\x00\x12N\n\x07observe\x12\x1f.llmsr_worker.pb.ObserveRequest\x1a .llmsr_worker.pb.ObserveResponse\"\x00\x42%Z#mictlan/orchestrator/internal/pb;pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'llmsr_worker.pb.llmsr_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z#mictlan/orchestrator/internal/pb;pb'
  _globals['_PROGRAM']._serialized_start=48
  _globals['_PROGRAM']._serialized_end=90
  _globals['_PROPOSEREQUEST']._serialized_start=92
  _globals['_PROPOSEREQUEST']._serialized_end=151
  _globals['_PROPOSERESPONSE']._serialized_start=153
  _globals['_PROPOSERESPONSE']._serialized_end=189
  _globals['_OBSERVEREQUEST']._serialized_start=191
  _globals['_OBSERVEREQUEST']._serialized_end=225
  _globals['_OBSERVERESPONSE']._serialized_start=227
  _globals['_OBSERVERESPONSE']._serialized_end=277
  _globals['_LLMSR']._serialized_start=280
  _globals['_LLMSR']._serialized_end=447
# @@protoc_insertion_point(module_scope)
