#!/usr/bin/env python3

import argparse
from workspace import util
import json


def main():
    parser = argparse.ArgumentParser(
        description='指定されたパターンにマッチするファイルの内容を出力')
    parser.add_argument('pattern', type=str)
    args = parser.parse_args()

    contents = util.readfiles(args.pattern)
    print(json.dumps(contents, indent=2))


if __name__ == "__main__":
    main()
