#!/usr/bin/env python

import argparse
from workspace import secret, path


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Secret ファイルの import/export を行います。"
    )
    # 位置引数で操作を指定（必須）
    parser.add_argument(
        "operation",
        choices=["import", "export"],
        help="実行する操作: 'export' でシークレットを tar に固め、'import' で tar から展開します。"
    )
    # 位置引数でシークレットファイルの場所（任意、デフォルトは ".secrets"）
    parser.add_argument(
        "secrets",
        nargs="?",
        default=".secrets",
        help="シークレットファイルの場所（デフォルト: .secrets）"
    )
    # 位置引数で tar アーカイブのパス（任意、デフォルトは "secrets2.tar.gz"）
    parser.add_argument(
        "archive",
        nargs="?",
        default="secrets2.tar.gz",
        help="tar アーカイブのパス（デフォルト: secrets.tar.gz）"
    )
    args = parser.parse_args()

    # SecretsFileRepo の初期化（引数で指定されたシークレットの場所を使用）
    repo = secret.SecretsFileRepo(path.Path(args.secrets))
    packer = secret.TarPacker()
    manager = secret.Manager(repo, packer)
    archive_path = path.Path(args.archive)

    if args.operation == "export":
        manager.export(archive_path)
        print(f"Secrets を tar アーカイブ '{archive_path}' にエクスポートしました。")
    elif args.operation == "import":
        manager.import_(archive_path)
        print(f"tar アーカイブ '{archive_path}' から Secrets をインポートしました。")
    else:
        # この分岐は実際には到達しません
        raise ValueError("無効な操作です。")


if __name__ == '__main__':
    main()
