input:
  kafka_franz:
    auto_replay_nacks: true
    consumer_group: zaiko.stock.projector
    seed_brokers:
    - redpanda:9092
    topics:
    - zaiko.stock.projections
output:
  stdout: {}
pipeline:
  processors:
  - schema_registry_decode:
      url: http://redpanda:8081
  - try:
    - resource: sales_stocks_mongo
  - catch:
    - log:
        message: 'Processing failed due to: ${!error()}'
processor_resources:
- label: sales_stocks_mongo
  mongodb:
    collection: sales_stocks
    database: zaiko
    document_map: '

      root.Sub = this.Sub

      root.Stocks = this.Stocks

      root.Sales = this.Sales

      '
    filter_map: root.Sub = this.Sub
    operation: replace-one
    upsert: true
    url: mongodb://mongo:27017
    write_concern:
      j: true
      w: majority
